name: Code Coverage

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Coveralls
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: Build & test with Maven and coverage
        run: mvn clean test
      - name: Post to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: jacoco